[athlete]
ftp = 263
weight = 76.4
lthr = 160
max_hr = 175
lt1 = 131

[plan]
start_date = "2026-02-09"
weeks = 25
event_date = "2026-08-04"

[intervals]
athlete_id = "0"

[phases]
# [start_week, end_week, min_hours, max_hours]
base_rebuild = [1, 4, 8, 12]
base_build = [5, 8, 10, 13]
build_1 = [9, 12, 12, 14]
build_2 = [13, 16, 13, 15]
endurance_specialty = [17, 20, 14, 18]
peak_specificity = [21, 24, 13, 15]
taper = [25, 25, 7, 8]

[zones]
# Power zones as % FTP upper bounds
z1 = 55
z2 = 75
z3 = 90
z4 = 105
z5 = 120
z6 = 150

[fatigue]
tsb_warning = -20
power_reduction = 0.05
eftp_drift_threshold = 5
